name: Java CI with Gradle

on:
  - push
  - pull_request
    

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@main
      - uses: gradle/actions/wrapper-validation@main
      - name: Set up JDK
        uses: graalvm/setup-graalvm@main
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Fix Gradle permissions
        run: chmod +x gradlew

      - name: Configure git
        run: git config --global user.email "noreply@github.com" && git config --global user.name "GitHub-Actions"

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Rename the jar
        run: mv build/libs/zones-1.0-dev.jar build/libs/Zones-${{ github.sha }}.jar

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs/Zones*.jar

      - name: Release dev build
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push'
        with:
          files: build/libs/Zones*.jar
          prerelease: true
          tag_name: latest-dev
          generate_release_notes: true

    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
